apiVersion: apps/v1
kind: Deployment
metadata:
  name: booktrack-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booktrack
  template:
    metadata:
      labels:
        app: booktrack
    spec:
      containers:
        - name: booktrack-container
          image: dariuslim744/booktrack-image:latest
          ports:
            - containerPort: 5500 # Matches the container port in Docker Compose
